tasks:
    - name: Setup & Build
      before: sdk install java 17.0.2-tem < /dev/null
      init: mvn clean install -DskipTests=true
vscode:
    extensions:
        - "vscjava.vscode-java-pack"
        - "cucumberopen.cucumber-official"
